# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qrcode.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'qrcode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cqrcode.proto\x12\x06qrcode\".\n\rQrCodeRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\"$\n\x0eQrCodeResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x32L\n\x0fQrCodeGenerator\x12\x39\n\x08Generate\x12\x15.qrcode.QrCodeRequest\x1a\x16.qrcode.QrCodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qrcode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QRCODEREQUEST']._serialized_start=24
  _globals['_QRCODEREQUEST']._serialized_end=70
  _globals['_QRCODERESPONSE']._serialized_start=72
  _globals['_QRCODERESPONSE']._serialized_end=108
  _globals['_QRCODEGENERATOR']._serialized_start=110
  _globals['_QRCODEGENERATOR']._serialized_end=186
# @@protoc_insertion_point(module_scope)
